
def function1(){
    stage("pilica first test") {
        node {
            cleanWs()
            checkout scm
            dir("${WORKSPACE}//Linux") {
                sh 'touch myfile'
            }
        }
    }
}
parallel "ACC1604 SGX1-FLC Container RelWithDebInfo" : { function1() }